apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

namespace: devops-dev

images:
- name: ghcr.io/hjmoons/devops-portal-backend
  newName: ghcr.io/hjmoons/devops-portal-backend
  newTag: 20260206-7f7abae

patches:
- path: deployment-patch.yaml
