apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: devops-prod

replicas:
  - name: portal-backend
    count: 2
  - name: portal-frontend
    count: 2

images:
  - name: ghcr.io/hjmoons/devops-portal-backend
    newTag: latest
  - name: ghcr.io/hjmoons/devops-portal-frontend
    newTag: latest
