apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: devops-dev

images:
- name: ghcr.io/hjmoons/devops-portal-frontend
  newName: ghcr.io/hjmoons/devops-portal-frontend
  newTag: 20260203-459b972
