server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application:
    name: devops
  datasource:
    url: jdbc:h2:file:./data/devops
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: portal
            client-secret: ZDK3y4gU1kkGOvKV6yYm1iSVMLaGlrDy
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/devops
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/devops

springdoc:
  swagger-ui:
    oauth:
      client-id: portal
      use-pkce-with-authorization-code-grant: true

jenkins:
  url: http://localhost:8080
  username: admin
  token: 11e7cf2c5bda806c6f0260162ad60588b7

github:
  url: https://api.github.com
  token: ${GITHUB_TOKEN:your-github-personal-access-token}