apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: portal-api.devops.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: portal-backend
                port:
                  number: 8090
